version: '3'
services:
  redis:
    image: redis:latest
    container_name: rd01

  webapp:
    build: .
    container_name: wa01
    ports:
      - '8000:8000'
    links:
      - redis
    depends_on:
      - redis
    command: >
      sh -c "python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"

  celery:
    build: .
    volumes:
      - .:/webapp
    container_name: cl01
    command: celery -A core worker -l info
    links:
      - redis
