version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code

    ports:
      - 8000:8000
  redis:
    image: redis:7

  celery:
    build: .
    restart: always
    command: celery beat -A core --loglevel=info
    volumes:
      - .:/code

    depends_on:
      - redis
      - web
