# Generated by Django 4.0 on 2024-02-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(3, 'High'), (2, 'Medium'), (1, 'Low')], max_length=1),
        ),
    ]
